from PySide6.QtCore import QSize
from PySide6.QtGui import QPixmap, Qt, QPainter, QIcon

from pyside_arco_widget.common.icon.svg import SVGRenderer, SvgEnum


class Icon:
    def __init__(self, renderer: SVGRenderer, spin: bool = False, repaint=None, size: QSize = QSize(24, 24)):
        self.renderer = renderer
        self._size = size
        self.repaint = repaint
        self.spin = spin

    def isNull(self):
        return self.renderer is None

    @property
    def spin(self):
        return self.renderer.rotated

    @spin.setter
    def spin(self, spin: bool):
        self.renderer.setRotated(spin)
        if spin:
            if self.repaint:
                self.renderer.repaintNeeded.connect(lambda: self.repaint(self.icon))
        else:
            self.renderer.repaintNeeded.disconnect()

    @property
    def icon(self):
        pixmap = QPixmap(self._size)
        pixmap.fill(Qt.transparent)
        painter = QPainter(pixmap)
        self.renderer.render(painter)
        painter.end()
        pixmap = pixmap.scaled(self._size)
        icon = QIcon()
        icon.addPixmap(pixmap, QIcon.Mode.Normal)
        icon.addPixmap(pixmap, QIcon.Mode.Disabled)
        return icon


class ArcoIcon(SvgEnum):
    AlignCenter = 'align-center'
    AlignLeft = 'align-left'
    AlignRight = 'align-right'
    Apps = 'apps'
    Archive = 'archive'
    ArrowDown = 'arrow-down'
    ArrowFall = 'arrow-fall'
    ArrowLeft = 'arrow-left'
    ArrowRight = 'arrow-right'
    ArrowRise = 'arrow-rise'
    ArrowUp = 'arrow-up'
    At = 'at'
    Attachment = 'attachment'
    Backward = 'backward'
    BgColors = 'bg-colors'
    Bold = 'bold'
    Book = 'book'
    Branch = 'branch'
    Brush = 'brush'
    Bug = 'bug'
    Bulb = 'bulb'
    Calendar = 'calendar'
    CalendarClock = 'calendar_clock'
    Camera = 'camera'
    CaretDown = 'caret-down'
    CaretLeft = 'caret-left'
    CaretRight = 'caret-right'
    CaretUp = 'caret-up'
    Check = 'check'
    CheckCircle = 'check-circle'
    CheckCircleFill = 'check-circle-fill'
    CheckSquare = 'check-square'
    ChineseFill = 'chinese-fill'
    ClockCircle = 'clock-circle'
    Close = 'close'
    CloseCircle = 'close-circle'
    CloseCircleFill = 'close-circle-fill'
    Cloud = 'cloud'
    CloudDownload = 'cloud-download'
    Code = 'code'
    CodeBlock = 'code-block'
    CodeSquare = 'code-square'
    Command = 'command'
    Common = 'common'
    Compass = 'compass'
    Copy = 'copy'
    Copyright = 'copyright'
    CustomerService = 'customer-service'
    Dashboard = 'dashboard'
    Delete = 'delete'
    Desktop = 'desktop'
    Dice = 'dice'
    DoubleDown = 'double-down'
    DoubleLeft = 'double-left'
    DoubleRight = 'double-right'
    DoubleUp = 'double-up'
    Down = 'down'
    DownCircle = 'down-circle'
    Download = 'download'
    DragArrow = 'drag-arrow'
    DragDot = 'drag-dot'
    DragDotVertical = 'drag-dot-vertical'
    DriveFile = 'drive-file'
    Ear = 'ear'
    Edit = 'edit'
    Email = 'email'
    Empty = 'empty'
    EnglishFill = 'english-fill'
    Eraser = 'eraser'
    Exclamation = 'exclamation'
    ExclamationCircle = 'exclamation-circle'
    ExclamationCircleFill = 'exclamation-circle-fill'
    ExclamationPolygonFill = 'exclamation-polygon-fill'
    Expand = 'expand'
    Experiment = 'experiment'
    Export = 'export'
    Eye = 'eye'
    EyeInvisible = 'eye-invisible'
    FaceFrownFill = 'face-frown-fill'
    FaceMehFill = 'face-meh-fill'
    FaceSmileFill = 'face-smile-fill'
    File = 'file'
    FileAudio = 'file-audio'
    FileImage = 'file-image'
    FilePdf = 'file-pdf'
    FileVideo = 'file-video'
    Filter = 'filter'
    FindReplace = 'find-replace'
    Fire = 'fire'
    Fold = 'fold'
    Folder = 'folder'
    FolderAdd = 'folder-add'
    FolderDelete = 'folder-delete'
    FontColors = 'font-colors'
    Formula = 'formula'
    Forward = 'forward'
    Fullscreen = 'fullscreen'
    FullscreenExit = 'fullscreen-exit'
    General = 'general'
    Gift = 'gift'
    H1 = 'h1'
    H2 = 'h2'
    H3 = 'h3'
    H4 = 'h4'
    H5 = 'h5'
    H6 = 'h6'
    H7 = 'h7'
    Heart = 'heart'
    HeartFill = 'heart-fill'
    Highlight = 'highlight'
    History = 'history'
    Home = 'home'
    Idcard = 'idcard'
    Image = 'image'
    ImageClose = 'image-close'
    Import = 'import'
    Info = 'info'
    InfoCircle = 'info-circle'
    InfoCircleFill = 'info-circle-fill'
    Interaction = 'interaction'
    Italic = 'italic'
    Language = 'language'
    Launch = 'launch'
    Layout = 'layout'
    Left = 'left'
    LeftCircle = 'left-circle'
    LineHeight = 'line-height'
    Link = 'link'
    List = 'list'
    LiveBroadcast = 'live-broadcast'
    Loading = 'loading'
    Location = 'location'
    Lock = 'lock'
    Loop = 'loop'
    Man = 'man'
    Menu = 'menu'
    MenuFold = 'menu-fold'
    MenuUnfold = 'menu-unfold'
    Message = 'message'
    MessageBanned = 'message-banned'
    MindMapping = 'mind-mapping'
    Minus = 'minus'
    MinusCircle = 'minus-circle'
    MinusCircleFill = 'minus-circle-fill'
    Mobile = 'mobile'
    Moon = 'moon'
    MoonFill = 'moon-fill'
    More = 'more'
    MoreVertical = 'more-vertical'
    Mosaic = 'mosaic'
    Music = 'music'
    Mute = 'mute'
    MuteFill = 'mute-fill'
    Nav = 'nav'
    Notification = 'notification'
    NotificationClose = 'notification-close'
    ObliqueLine = 'oblique-line'
    OldVersion = 'old-version'
    OrderedList = 'ordered-list'
    OriginalSize = 'original-size'
    Palette = 'palette'
    Paste = 'paste'
    Pause = 'pause'
    PauseCircle = 'pause-circle'
    PauseCircleFill = 'pause-circle-fill'
    Pen = 'pen'
    PenFill = 'pen-fill'
    Phone = 'phone'
    PlayArrow = 'play-arrow'
    PlayArrowFill = 'play-arrow-fill'
    PlayCircle = 'play-circle'
    PlayCircleFill = 'play-circle-fill'
    Plus = 'plus'
    PlusCircle = 'plus-circle'
    PlusCircleFill = 'plus-circle-fill'
    Poweroff = 'poweroff'
    Printer = 'printer'
    Public = 'public'
    Pushpin = 'pushpin'
    Qrcode = 'qrcode'
    Question = 'question'
    QuestionCircle = 'question-circle'
    QuestionCircleFill = 'question-circle-fill'
    Quote = 'quote'
    Record = 'record'
    RecordStop = 'record-stop'
    Redo = 'redo'
    Refresh = 'refresh'
    Reply = 'reply'
    Right = 'right'
    RightCircle = 'right-circle'
    Robot = 'robot'
    RobotAdd = 'robot-add'
    RotateLeft = 'rotate-left'
    RotateRight = 'rotate-right'
    Safe = 'safe'
    Save = 'save'
    Scan = 'scan'
    Schedule = 'schedule'
    Scissor = 'scissor'
    Search = 'search'
    SelectAll = 'select-all'
    Send = 'send'
    Settings = 'settings'
    Shake = 'shake'
    ShareAlt = 'share-alt'
    ShareExternal = 'share-external'
    ShareInternal = 'share-internal'
    Shrink = 'shrink'
    Skin = 'skin'
    SkipNext = 'skip-next'
    SkipNextFill = 'skip-next-fill'
    SkipPrevious = 'skip-previous'
    SkipPreviousFill = 'skip-previous-fill'
    Sort = 'sort'
    SortAscending = 'sort-ascending'
    SortDescending = 'sort-descending'
    Sound = 'sound'
    SoundFill = 'sound-fill'
    Stamp = 'stamp'
    Star = 'star'
    StarFill = 'star-fill'
    Stop = 'stop'
    Storage = 'storage'
    Strikethrough = 'strikethrough'
    Subscribe = 'subscribe'
    SubscribeAdd = 'subscribe-add'
    Subscribed = 'subscribed'
    Sun = 'sun'
    SunFill = 'sun-fill'
    Swap = 'swap'
    Sync = 'sync'
    Tag = 'tag'
    Tags = 'tags'
    ThumbDown = 'thumb-down'
    ThumbDownFill = 'thumb-down-fill'
    ThumbUp = 'thumb-up'
    ThumbUpFill = 'thumb-up-fill'
    Thunderbolt = 'thunderbolt'
    ToBottom = 'to-bottom'
    ToLeft = 'to-left'
    ToRight = 'to-right'
    ToTop = 'to-top'
    Tool = 'tool'
    Translate = 'translate'
    Trophy = 'trophy'
    Underline = 'underline'
    Undo = 'undo'
    Unfold = 'unfold'
    Unlock = 'unlock'
    UnorderedList = 'unordered-list'
    Up = 'up'
    UpCircle = 'up-circle'
    Upload = 'upload'
    User = 'user'
    UserAdd = 'user-add'
    UserGroup = 'user-group'
    VideoCamera = 'video-camera'
    Voice = 'voice'
    Wifi = 'wifi'
    Woman = 'woman'
    ZoomIn = 'zoom-in'
    ZoomOut = 'zoom-out'
